name: ESP-IDF Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Make mock secrets.hpp
      run: mv src/secrets.hpp.example src/secrets.hpp
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@latest
    
